function L = calc_L(e)

arguments
    e (4,1) double
end

% E = [e(1) -e(4)  e(3)  e(2);...
%      e(4)  e(1) -e(2)  e(3);...
%     -e(3)  e(2)  e(1)  e(4);...
%     -e(2) -e(3) -e(4)  e(1)]; % From Ashley's dissertation

% E = [e(4)  e(3) -e(2) -e(1);...
%     -e(3)  e(4)  e(1) -e(2);...
%      e(2) -e(1)  e(4) -e(3);...
%      e(1)  e(2)  e(3)  e(4)]'; % From Dr. Bowling's book

L = 2*[-e(2)  e(1)  e(4) -e(3);...
       -e(3) -e(4)  e(1)  e(2);...
       -e(4)  e(3) -e(2)  e(1)]; % From online pdf
end